=== nikkisingh12/xmlRepo/xml_project/src/movies.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT movies (movie+)>
<!ELEMENT movie (code,title,release_date?,theatre_name,city+)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT release_date (day,month,year)>
<!ELEMENT day (#PCDATA)>
<!ELEMENT month (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT theatre_name (#PCDATA)>
<!ELEMENT city (#PCDATA)>

=== nikkisingh12/xmlRepo/xml_project/src/moviesinfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE movies SYSTEM "movies.dtd" >
<movies>
  <movie>
    <code>code</code>
    <title>kabir singh</title>
    <release_date>
    <day>12</day>
    <month>7</month>
    <year>2019</year>
    
    </release_date>
    <theatre_name>pvr</theatre_name>
    <city>pune</city>
    <city>mumbai</city>
    <city>delhi</city>
  </movie>
</movies>

<movies>
<code> 105</code>
<title> sholey</title>
<theatre> inox</theatre>
</movies>
